version: "3"

services:
  # Servers
  appserver:
    image: tu2bo-appserver_app
    build:
      context: ./tu2bo-appserver/app
      dockerfile: Dockerfile.web
    environment: 
      - PORT=5000
      - AUTH_URI=http://authserver:3000
      - MEDIA_URI=http://media-srv:5005
      - TUTUBO_ENV=PROD
      - MONGODB_URI=mongodb://appserver-db:27017/appserver-db
    ports:
      - "5000:5000"
    networks:
      - default
      - appserver-network
      - system-network
  
  authserver:
    image: tu2bo-authserver_app
    build:
      context: ./tu2bo-authserver/app
      dockerfile: Dockerfile.web
    environment: 
      - PORT=3000
      - TUTUBO_ENV=PROD
      - MONGODB_URI=mongodb://authserver-db:27017/authserver-db
    ports:
      - "3000:3000"
    networks:
      - authserver-network
      - system-network
  
  media-srv:
    image: tu2bo-media-srv_app
    build:
      context: ./tu2bo-media-srv
      dockerfile: Dockerfile.web
    environment: 
      - PORT=5005
      - TUTUBO_ENV=PROD
      - MONGODB_URI=mongodb://media-srv-db:27017/media-srv-db
    ports:
      - "5005:5005"
    networks:
      - media-srv-network
      - system-network
    depends_on:
      - media-srv-db

  # DBs
  appserver-db:
    image: mongo:3.6.4
    networks:
      - appserver-network

  authserver-db:
    image: mongo:3.6.4
    networks:
      - authserver-network

  media-srv-db:
    image: mongo:3.6.4
    networks:
      - media-srv-network

networks:
  appserver-network:
  authserver-network:
  media-srv-network:
  system-network:
